version: '3.9'

services:
  database:
    container_name: targetlayer_database
    image: postgres:16.4
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - targetlayer_network

  ollama:
    container_name: targetlayer_ollama
    image: ollama/ollama:latest
    restart: always
    hostname: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    networks:
      - targetlayer_network

  api:
    container_name: targetlayer_api
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - POSTGRES_HOST=database
    ports:
      - "8000:8000"
    depends_on:
      - database
      - ollama
    networks:
      - targetlayer_network

volumes:
  postgres_data:
  ollama_data:

networks:
  targetlayer_network:
    driver: bridge